services:
  - type: web
    name: personal-finance-tracker
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn finance_tracker.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: pft-db
          property: connectionString

databases:
  - name: pft-db
    plan: free
